stages:
  - build

before_script:
    - apt-get update
    - apt-get install -y plantuml
    - ls *.*uml
  
generer_PNG_PlantUML:
    stage: build
    script:
        - plantuml -v -charset UTF-8 -o PNG/ "*.*uml*"

    artifacts:
        name: "$CI_COMMIT_SHORT_SHA UML_PNG"
        paths:
            - PNG/